---

name: Authenticate with Amazon ECR
description: Authenticate with Amazon ECR
author: aereal
branding:
  color: orange
  icon: log-in
outputs:
  username:
    description: retrieved ECR username
    value: ${{ steps.authen.outputs.username }}
  password:
    description: retrieved ECR username
    value: ${{ steps.authen.outputs.password }}
  server:
    description: ECR repository server name
    value: ${{ steps.authen.outputs.server }}
runs:
  using: composite
  steps:
    - name: restore cache
      id: use-cache
      uses: actions/cache@v3.0.2
      with:
        path: /opt/authen-amazon-ecr
        key: authen-amazon-ecr-1.1.0
    - uses: actions/setup-go@v3.0.0
      if: ${{ ! steps.use-cache.outputs.cache-hit }}
      with:
        go-version: '1.18.x'
    - uses: actions/checkout@v3.0.1
      if: ${{ ! steps.use-cache.outputs.cache-hit }}
    - uses: actions/cache@v3.0.2
      if: ${{ ! steps.use-cache.outputs.cache-hit }}
      with:
        path: ~/go/pkg/mod
        key: authen-amazon-ecr-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          authen-amazon-ecr-go-
    - name: build
      if: ${{ ! steps.use-cache.outputs.cache-hit }}
      shell: bash
      run: |
        go mod download
        go build -o /opt/authen-amazon-ecr/bin/authen-amazon/ecr ./cmd/authen-amazon-ecr
    - name: run authenticate-amazon-ecr
      id: authen
      shell: bash
      run: /opt/authen-amazon-ecr/bin/authen-amazon-ecr
