---

builds:
  -
    main: ./cmd/authen-amazon-ecr
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
release:
  mode: keep-existing
