---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - uses: reviewdog/action-golangci-lint@v2.1.3
        with:
          level: warning
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: '1.18.x'
      - uses: actions/cache@v3.0.2
        with:
          path: ~/go/pkg/mod
          key: go-1.18.x-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ matrix.go_version }}-
      - name: test
        run: go test -v -race -coverprofile=cover.txt ./...
      - name: upload coverage
        uses: codecov/codecov-action@v3.0.0
        with:
          files: ./cover.txt
