---

# from https://github.com/r7kamura/workflows/blob/main/.github/workflows/keep-main-version-branch.yml

name: Keep main version branch
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: push to main version branch
        run: |
          branch_name=$(echo "${GITHUB_REF_NAME}" | sed -E "s/(v[0-9+])\..+/\1/")
          git push --force origin "HEAD:refs/heads/${branch_name}"
